/var/spool/slurmd/job2286419/slurm_script: line 13: conda: command not found
[I 2024-12-05 14:09:10,403] A new study created in RDB with name: Pk_nwLH_params_transfer_497
/home/vk9342/USRP2024/pytorch/data.py:13: RuntimeWarning: invalid value encountered in log10
  Pk = np.log10(np.load(f_Pk))
CUDA Available
slurmstepd: error: *** JOB 2286419 ON adroit-h11g2 CANCELLED AT 2024-12-05T14:10:11 ***
