/var/spool/slurmd/job2286383/slurm_script: line 13: conda: command not found
[I 2024-12-05 13:21:53,158] A new study created in RDB with name: Pk_nwLH_params_transfer_497
[W 2024-12-05 13:21:54,159] Trial 0 failed with parameters: {'lr': 0.012302118390347632, 'wd': 8.182733236764e-05, 'n_layers': 1, 'n_units_l0': 456, 'dropout_l0': 0.7873316758464115} because of the following error: FileNotFoundError(2, 'No such file or directory').
Traceback (most recent call last):
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main_continue.py", line 64, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 80, in create_dataset
    data_set = make_dataset(mode, seed, f_Pk, f_Pk_norm, f_params, cosm_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 13, in __init__
    Pk = np.log10(np.load(f_Pk))
                  ^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'all_Pk_nwLH_497.npy'
[W 2024-12-05 13:21:54,161] Trial 0 failed with value None.
CUDA Available
Traceback (most recent call last):
  File "/home/vk9342/USRP2024/pytorch/main_continue.py", line 199, in <module>
    study.optimize(objective, n_trials, n_jobs=n_jobs)
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 62, in _optimize
    _optimize_sequential(
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 159, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 247, in _run_trial
    raise func_err
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/main_continue.py", line 64, in __call__
    train_loader = data.create_dataset('train', self.seed, f_Pk, f_Pk_norm, 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 80, in create_dataset
    data_set = make_dataset(mode, seed, f_Pk, f_Pk_norm, f_params, cosm_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vk9342/USRP2024/pytorch/data.py", line 13, in __init__
    Pk = np.log10(np.load(f_Pk))
                  ^^^^^^^^^^^^^
  File "/home/vk9342/.conda/envs/usrp/lib/python3.11/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'all_Pk_nwLH_497.npy'
